# These are supported funding model platforms

github: maseshi
patreon: maseshi
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
custom: ["https://www.buymeacoffee.com/maseshi", Buy me a coffee]
