#!/bin/sh -x

clear
echo Start with start.sh in administrator mode....
echo Initiate component update...
sudo apt-get update
echo The component update is complete.
echo Installing components...
sudo npm install --save
echo Completing the component installation.
echo Starting the system...
sudo node ./source/shard.js
