name: Node.js CI

on:
  push:
    branches: [ stable, beta ]
    paths-ignore:
      - README.md
      - .github/
      - package.json
  pull_request:
    branches: [ stable, beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        super_secret: ${{ secrets.SuperSecret }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
